### ISSUE TITLE
无法检测到摄像头

### ISSUE THREAD

**Issue by trebladev** [unitreerobotics/UnitreecameraSDK#1]
我用笔记本连接了go1的局域网并且可以控制机器人移动，但是我运行 ./bins/example_getRawFrame的时候出现如下报错
`[UnitreeCameraSDK][ERROR] read to tmp file failed, maybe mkstemp file error!
 [UnitreeCameraSDK][ERROR] This camera cannot get internal parameters! 
[UnitreeCameraSDK][ERROR] You should flash the calibration parameters or load it from disk. 
Segmentation fault`
请问应该怎么设置，谢谢

**Comment by Zhaiweiwei0** [comment]
@dnaglucose

**Comment by dnaglucose** [comment]
问题：读取不到相机配置文件。这个问题比较复杂：
A、相机连接中断：在终端下  ls /dev/video*  查看相机设备号列表
如果列表为空，重启狗，连续3次均是此种状况，代表相机断开连接，需要联系售后部门
B、启动目录/端口错误：1、核对一下你的启动目录，并且查看example_getRawFrame.cc文件中UnitreeCamera cam("") 引号范围内的启动yaml配置文件，路径是否正确。
2、查看yaml配置文件中DeviceNode一项值，是否和 ls /dev/video* 相机端口返回值一致，不一致则修改到一致

**Comment by trebladev** [comment]
你好，
       我在狗自带的nano上能够用 ls /dev/video*识别到两个video设备，但是当我想在nano上调用摄像头的时候出现了这样的错误
   `[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (1757) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v412src0 reported: Internal data stream error.

[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (886)open OpenCV | GStreamer warning: unable to start pipeline

[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpencV GStreamer Warning: GStreamer: pipeline have not been created`
       电脑连接上狗的局域网之后在电脑上执行 ls /dev/video*没有看到新的摄像头设备，但是在手机的app(官方app)中能看到摄像头的视频。
       想请问这样的情况是摄像头断开连接还是什么别的情况

**Comment by dnaglucose** [comment]
使用方式有误，所有的sdk范例只支持在狗运行的板子上面执行。

 ls /dev/video* 只是显示链接在当前平台上的视频输入设备，相机链接在nano上而非pc上。

**Comment by trebladev** [comment]
我在狗自带的nano上运行 ./bins/example_getRawFrame，检查了devicenode和ls /dev/video*显示中的对的上，还是出现了和上面一样的报错
`[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (1757) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v412src0 reported: Internal data stream error.

[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (886)open OpenCV | GStreamer warning: unable to start pipeline

[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpencV GStreamer Warning: GStreamer: pipeline have not been created`
请问这个是什么问题

**Comment by dnaglucose** [comment]
抱歉，之前理解产生了偏差
`[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (1757) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v412src0 reported: Internal data stream error.

[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (886)open OpenCV | GStreamer warning: unable to start pipeline

[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpencV GStreamer Warning: GStreamer: pipeline have not been created`

这三行警报提示不会影响使用，忽略这个警告即可。
相机不启动是因为固有的程序占用了设备资源。
如果使用sdk，请关闭自动启动的程序。ps -ef |grep point   然后kill掉，才可使用sdk

**Comment by trebladev** [comment]
确实是这个问题，问题已经解决，感谢回复。

**Comment by geyang** [comment]
找不到这个文件夹，是在哪一个 机器上面有这个文件夹呀？

> 如果使用sdk，请关闭自动启动的占用相机硬件资源的程序。ps -ef |grep point 然后kill掉相关程序，才可使用sdk。也可以运行/unitree/autostart/02camerarosnode/cameraRosNode中的kill.sh脚本

**Update:** 找到了，在 `~/Unitree`

**Comment by snailsssss** [comment]
你好 我们的13板卡也出现了这样的问题。[UnitreeCameraSDK][ERROR] read to tmp file failed, maybe mkstemp file error! [UnitreeCameraSDK][ERROR] This camera cannot get internal parameters!  [UnitreeCameraSDK][ERROR] You should flash the calibration parameters or load it from disk.  Segmentation fault。我们尝试了A、相机连接中断：在终端下 ls /dev/video* 查看相机设备号列表。我们发现在13板卡上dev文件夹里没有video配置文件。在14 15 板卡是有的。请问要怎么恢复这个文件？
