### ISSUE TITLE
Unable to execute example_getDepthFrame with Go1

### ISSUE THREAD

**Issue by constantpi** [unitreerobotics/UnitreecameraSDK#21]
Hello,

I have been using the Unitree Go1 and am interested in acquiring depth images from the camera. Upon executing example_getRawFrame, I have confirmed that I am able to retrieve the RGB images. However, I am unable to execute other functions such as example_getDepthFrame and example_getPointCloud. The specific errors are as follows:

```
unitree@unitree-desktop:~/Unitree/sdk/UnitreecameraSDK/bins$ ./example_getDepthFrame
Invalid deviceNode!
Segmentation fault (core dumped)
```

I would greatly appreciate any assistance or guidance in resolving this issue.

**Comment by LiqunXu** [comment]
The directory to the stereo_camera_config.yaml need to be set as "../stereo_camera_config.yaml".

**Comment by constantpi** [comment]
This problem was resolved thanks to your support.
