### ISSUE TITLE
Could I put the Depth or PointCloud data via UDP ?

### ISSUE THREAD

**Issue by devemin** [unitreerobotics/UnitreecameraSDK#3]
Hello,

**[Question]**
I would like to know only about can I put the Depth or PointCloud data via UDP ?

(I couldn't find about it from documents.)

<br>

**[Supplement]**
I tried the example putImagetrans.cc & getimagetrans.cc .
I succeed to put the video via UDP.
But I couldn't put the Depth at the server side.

![image](https://user-images.githubusercontent.com/52738228/161235948-fe994666-2a94-4cd8-91b9-e50b6e28a20c.png)

[My Twitter](https://twitter.com/devemin/status/1509783551948226560)

(Did ~/Unitree/autostart/camerarosnode/cameraRosnode/kill.sh )

```
pattern (A, video streaming)

>>cam.startCapture(true,false); ///< disable share memory sharing and able image h264 encoding
```

I tried this.

```
pattern (B, try to do depth streaming)

    cam.startCapture();                 //disable both.
    cam.startStereoCompute();
        --------------
        if(!cam.getDepthFrame(depth, true, t)){
        --------------
```

But the server side couldn't put the Depth.

![WIN_20220401_18_18_19_Pro](https://user-images.githubusercontent.com/52738228/161234501-36ea1c23-efa9-4154-956c-5b494fde4f30.jpg)

If the stream start with Videos, It appear the IP address and port No.
But with depth (pattern(B) ) , console string stopped. it didn't appear the IP address and port No.

I guess that I should disable the h264 encoding, but I can't find about it from the documents.

Could you answer about the question ?

**Comment by devemin** [comment]
I try this again.

I succeed to send origin / rect / depth image.
But maybe can't send the PointCloud data.

I make a new transferring example.
https://github.com/unitreerobotics/UnitreecameraSDK/pull/5

Thanks.

**Comment by nicolasukd** [comment]
I dont think this is the same problem but im stuck with this https://github.com/unitreerobotics/UnitreecameraSDK/issues/15. Im just trying to generate a camera node where the topics are the specific camera data (depth, origin, rect, camera info, etc), do you have any idea?
